### ISSUE TITLE
Inefficient implementation of url search

### ISSUE THREAD

**Issue by sainihitesh** [vipulbhj/clean-url#1]
https://github.com/vipulbhj/clean-url/blob/423fd57c8f96b8dd04b47541f5f2f77b7db358b6/index.js#L19

> It takes O(n) to search. it can be implemented in O(1) only.
see https://stackoverflow.com/questions/8877666/how-is-a-javascript-hash-map-implemented

**Comment by vipulbhj** [comment]
Yes I tried that implementation, but the issue is that the url we have in the data is not exactly the same as what we will get in the history. There can be different protocols, query parameters etc. I also tried Parsing the url which has been recieved from the get request and then using host section of that for Hashing. But that too is not consistent

**Comment by fxnoob** [comment]
we get url in the history using chrome apis.
url in the data file is in "www.hostname" format. 
we can encode both the urls to extract only hostname from it.
and that would be efficient approach.

**Comment by fxnoob** [comment]
see https://github.com/fxnoob/delete-sensitive-history/blob/fc50c82594395bac3a603f7e25be38197e38e44b/src/data/websites.json#L1

**Comment by vipulbhj** [comment]
There are issues with some url as they are followed with '\t'. Also some urls are messed up, see the 10th last entry. Also I would highly appreciate a PR

**Comment by fxnoob** [comment]
see also https://github.com/fxnoob/delete-sensitive-history/blob/55ccdec057bdcc529c0422762bfb5f5e8984cbd0/src/data/websites.json#L2

**Comment by fxnoob** [comment]
Now extension is in working stage. thanks for your great contribution. you can check that out by installing in chrome.  
Link : https://github.com/fxnoob/delete-sensitive-history

**Comment by vipulbhj** [comment]
I will definitely give it a try. :smiley:

**Comment by vipulbhj** [comment]
New implementation added, better support for url added and time complexity improved.
